# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FsFoodsaver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('bezirk_id', models.IntegerField()),
                ('position', models.CharField(max_length=255)),
                ('verified', models.IntegerField()),
                ('last_pass', models.DateTimeField()),
                ('new_bezirk', models.CharField(max_length=120)),
                ('want_new', models.IntegerField()),
                ('mailbox_id', models.IntegerField()),
                ('rolle', models.IntegerField()),
                ('type', models.IntegerField(blank=True, null=True)),
                ('plz', models.CharField(blank=True, max_length=10, null=True)),
                ('stadt', models.CharField(blank=True, max_length=100, null=True)),
                ('lat', models.CharField(blank=True, max_length=20, null=True)),
                ('lon', models.CharField(blank=True, max_length=20, null=True)),
                ('photo', models.CharField(blank=True, max_length=50, null=True)),
                ('photo_public', models.IntegerField()),
                ('email', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('passwd', models.CharField(blank=True, max_length=32, null=True)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('admin', models.IntegerField(blank=True, null=True)),
                ('nachname', models.CharField(blank=True, max_length=120, null=True)),
                ('anschrift', models.CharField(blank=True, max_length=120, null=True)),
                ('telefon', models.CharField(blank=True, max_length=30, null=True)),
                ('tox', models.CharField(blank=True, max_length=255, null=True)),
                ('homepage', models.CharField(blank=True, max_length=255, null=True)),
                ('github', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('handy', models.CharField(blank=True, max_length=50, null=True)),
                ('geschlecht', models.IntegerField(blank=True, null=True)),
                ('geb_datum', models.DateField(blank=True, null=True)),
                ('anmeldedatum', models.DateTimeField(blank=True, null=True)),
                ('orgateam', models.IntegerField(blank=True, null=True)),
                ('active', models.IntegerField()),
                ('data', models.TextField()),
                ('about_me_public', models.TextField()),
                ('newsletter', models.IntegerField(blank=True, null=True)),
                ('token', models.CharField(max_length=25)),
                ('infomail_message', models.IntegerField()),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('stat_fetchweight', models.DecimalField(decimal_places=2, max_digits=7)),
                ('stat_fetchcount', models.IntegerField()),
                ('stat_ratecount', models.IntegerField()),
                ('stat_rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('stat_postcount', models.IntegerField()),
                ('stat_buddycount', models.IntegerField()),
                ('stat_bananacount', models.IntegerField()),
                ('stat_fetchrate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sleep_status', models.IntegerField()),
                ('sleep_from', models.DateField()),
                ('sleep_until', models.DateField()),
                ('sleep_msg', models.TextField()),
                ('last_mid', models.DateField()),
                ('option', models.TextField()),
                ('beta', models.IntegerField()),
                ('fs_password', models.CharField(blank=True, max_length=50, null=True)),
                ('quiz_rolle', models.IntegerField()),
                ('contact_public', models.IntegerField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fs_foodsaver',
                'managed': False,
            },
        ),
    ]
