# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezirk_id', models.IntegerField(default=0)),
                ('position', models.CharField(max_length=255)),
                ('verified', models.IntegerField(default=0)),
                ('last_pass', models.DateTimeField(null=True)),
                ('new_bezirk', models.CharField(max_length=120)),
                ('want_new', models.IntegerField(default=0)),
                ('mailbox_id', models.IntegerField(null=True)),
                ('rolle', models.IntegerField(default=0)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('zip', models.CharField(blank=True, db_column='plz', max_length=10, null=True)),
                ('city', models.CharField(blank=True, db_column='stadt', max_length=100, null=True)),
                ('lat', models.CharField(blank=True, max_length=20, null=True)),
                ('lon', models.CharField(blank=True, max_length=20, null=True)),
                ('photo', models.CharField(blank=True, max_length=50, null=True)),
                ('photo_public', models.IntegerField(default=0)),
                ('email', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('passwd', models.CharField(blank=True, max_length=32, null=True)),
                ('first_name', models.CharField(blank=True, db_column='name', max_length=120, null=True)),
                ('admin', models.IntegerField(blank=True, null=True)),
                ('last_name', models.CharField(blank=True, db_column='nachname', max_length=120, null=True)),
                ('address', models.CharField(blank=True, db_column='anschrift', max_length=120, null=True)),
                ('phone', models.CharField(blank=True, db_column='telefon', max_length=30, null=True)),
                ('tox', models.CharField(blank=True, max_length=255, null=True)),
                ('homepage', models.CharField(blank=True, max_length=255, null=True)),
                ('github', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, db_column='handy', max_length=50, null=True)),
                ('geschlecht', models.IntegerField(blank=True, null=True)),
                ('geb_datum', models.DateField(blank=True, null=True)),
                ('anmeldedatum', models.DateTimeField(blank=True, null=True)),
                ('orgateam', models.IntegerField(blank=True, null=True)),
                ('active', models.IntegerField(default=0)),
                ('data', models.TextField()),
                ('about_me_public', models.TextField()),
                ('newsletter', models.IntegerField(blank=True, null=True)),
                ('token', models.CharField(max_length=25)),
                ('infomail_message', models.IntegerField(default=0)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('stat_fetchweight', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('stat_fetchcount', models.IntegerField(default=0)),
                ('stat_ratecount', models.IntegerField(default=0)),
                ('stat_rating', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('stat_postcount', models.IntegerField(default=0)),
                ('stat_buddycount', models.IntegerField(default=0)),
                ('stat_bananacount', models.IntegerField(default=0)),
                ('stat_fetchrate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('sleep_status', models.IntegerField(default=0)),
                ('sleep_from', models.DateField(null=True)),
                ('sleep_until', models.DateField(null=True)),
                ('sleep_msg', models.TextField(null=True)),
                ('option', models.TextField(default='')),
                ('beta', models.IntegerField(default=0)),
                ('fs_password', models.CharField(blank=True, max_length=50, null=True)),
                ('quiz_rolle', models.IntegerField(default=0)),
                ('contact_public', models.IntegerField(default=0)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fs_foodsaver',
                'managed': False,
            },
        ),
    ]
